### ISSUE TITLE
J377 (WH=>Turnur)

### ISSUE THREAD

**Issue by MorganKell** [goryn-clade/pathfinder#214] opened 2024-03-15 00:42 UTC
Hello, recently we got a J377 Worhole to Turnur in our chain. But we can't put it in pathfinder, because J377 ist unkown in a C3 and C4 (so far I can tell). With best regards MK

https://www.eve-scout.com/#/

**Comment by TyrHeimdalEVE** [comment] 2024-03-26 18:34
Hi,

I can confirm this is something that is fixed in the upcoming version due to be released in a day or two.

**Closed as completed by TyrHeimdalEVE** 2024-03-26 18:34 UTC
